# Eureka Client Configuration
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Security & JWT Configuration
app.jwt.secret=ApN9Fqws3AgyNtxMqrPMACosw7y1JTaduE+KVZ/tu8Y=
app.jwt.access-token-expiration-ms=86400000
app.jwt.refresh-token-expiration-ms=604800000

# Spring Mail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soleya.noreply@gmail.com
spring.mail.password=kpenbuefxfxmjmwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# RabbitMQ Configuration
spring.rabbitmq.host=
spring.rabbitmq.port=
spring.rabbitmq.username=
spring.rabbitmq.password=

# Actuator & Management
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
