# Centralized Shared Configuration for Online Railway Reservation System

# Eureka Client
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Security / JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.access-token-expiration-ms=86400000
app.jwt.refresh-token-expiration-ms=604800000

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soleya.noreply@gmail.com
spring.mail.password=cyvk teoc klal xwlq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JPA & Hibernate Common Defaults
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.flyway.enabled=false

# Actuator & Monitoring
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
